title = "Irfan Haziq's Site"
baseURL = 'https://brocapang.github.io/'
languageCode = 'en-us'
theme = "papermod"
enableInlineShortcodes = true
enableRobotsTXT = true
[pagination]

pagerSize = 6

[params]

defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true

[taxonomies]
tag = "tags"

[params.homeInfoParams]
Title = "My Personal Site"
Content = "Collection of blog from my projects"
[[params.socialIcons]]
name = "Github"
url = "https://github.com/broCapang"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/gnapac/"

[[menu.main]]
name = "Search"
url = "search/"
weight = 20

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 20

[outputs]
home = [ "HTML", "RSS", "JSON" ]

